[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = [
    "@metaplex-foundation/umi",
    "@metaplex-foundation/umi-bundle-defaults",
    "@metaplex-foundation/umi-rpc-web3js",
    "@metaplex-foundation/umi-uploader-irys",
    "@metaplex-foundation/mpl-token-metadata",
    "@trezor/connect-web",
    "@trezor/connect-common",
    "@trezor/env-utils"
  ]

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-inline' 'unsafe-eval';
      style-src 'self' https://fonts.googleapis.com 'unsafe-inline';
      img-src 'self' https: data: blob:;
      font-src 'self' https://fonts.gstatic.com;
      connect-src 'self' 
        https://*.supabase.co 
        wss://*.supabase.co 
        https://api.mainnet-beta.solana.com 
        https://*.solana-mainnet.quiknode.pro 
        wss://*.solana-mainnet.quiknode.pro 
        https://o4509111588225024.ingest.de.sentry.io 
        https://trumpillion.com/.netlify/functions/* 
        https://devnet.solana.com
        https://api.devnet.solana.com
        wss://api.devnet.solana.com
        https://arweave.net
        https://arweave.dev;
      worker-src 'self' blob:;
      frame-src 'none';
      object-src 'none';
      base-uri 'self';
      form-action 'self';
      frame-ancestors 'none';
      upgrade-insecure-requests;
    """
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Cache-Control = "public, max-age=31536000, immutable"
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization, x-application-name, Wallet"
    Access-Control-Max-Age = "86400"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200